name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt update && \
        sudo apt install -y cmake libpcre3-dev zlib1g-dev libunwind-dev upx;

    - run: bash ./build.sh;
      env:
        CC: clang

    - run: ./nginx -V;

    - uses: actions/upload-artifact@v2
      with:
        name: nginx
        path: ./nginx
