name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - run: |
        sudo apt update && \
        sudo apt install -y libpcre3-dev zlib1g-dev upx;

    - run: bash ./build.sh;
      env:
        CC: clang-14

    - run: ./nginx -V;

    - uses: actions/upload-artifact@main
      with:
        name: nginx
        path: ./nginx
